filetype off
let &runtimepath .= ','.expand('<sfile>:p:h:h')
filetype plugin indent on
syntax enable
set more
set noswapfile
set viminfo=

call plug#begin()
Plug 'junegunn/vader.vim'
Plug 'vim-test/vim-test'
call plug#end()
au TabEnter * -tabclose
